model:
  pretrained_model_name_or_path: /workspace/luoyajing/3d_pruning/TripoSG/pretrained_weights/TripoSG
  vae:
    num_tokens: 2048
  transformer:
    enable_local_cross_attn: true
    global_attn_block_ids:
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 14
    - 16
    - 18
    - 20
    global_attn_block_id_range: null
dataset:
  config:
  - /workspace/luoyajing/3d_pruning/demo_dataset/demo_dataset.json
  training_ratio: 0.9
  min_num_parts: 1
  max_num_parts: 8
  max_iou_mean: 0.5
  max_iou_max: 0.5
  shuffle_parts: true
  object_ratio: 0.3
  rotating_ratio: 0.2
  ratating_degree: 10
  train_data_dir: /workspace/luoyajing/datasets/objaverse_4_views_ele30
  eval_data_dir: /workspace/luoyajing/3d_pruning/demo_dataset
optimizer:
  name: adamw
  lr: 0.0001
  betas:
  - 0.9
  - 0.999
  weight_decay: 0.01
  eps: 1.0e-08
lr_scheduler:
  name: constant_warmup
  num_warmup_steps: 1000
  total_steps: 20
train:
  batch_size_per_gpu: 4
  epochs: 10
  grad_checkpoint: true
  weighting_scheme: logit_normal
  logit_mean: 0.0
  logit_std: 1.0
  mode_scale: 1.29
  cfg_dropout_prob: 0.1
  l1_loss_weight: 1
  data_loss_weight: 10
  training_objective: -v
  log_freq: 1
  early_eval_freq: 500
  early_eval: 1000
  eval_freq: 1000
  save_freq: 2000
  eval_freq_epoch: 5
  save_freq_epoch: 10
  ema_kwargs:
    decay: 0.9999
    use_ema_warmup: true
    inv_gamma: 1.0
    power: 0.75
  total_batch_size: 16
val:
  batch_size_per_gpu: 1
  nrow: 4
  min_num_parts: 2
  max_num_parts: 8
  num_inference_steps: 50
  max_num_expanded_coords: 100000000.0
  use_flash_decoder: false
  rendering:
    radius: 4.0
    num_views: 36
    fps: 18
  metric:
    cd_num_samples: 204800
    cd_metric: l2
    f1_score_threshold: 0.1
    default_cd: 1000000.0
    default_f1: 0.0
args:
  config: configs/mp8_nt2048.yaml
  tag: scaleup_mp8_nt512
  output_dir: output_triposg_mask
  resume_from_iter: None
  seed: '0'
  max_train_steps: '20'
  max_val_steps: '4'
  num_workers: '32'
  pin_memory: 'False'
  use_ema: 'True'
  scale_lr: 'False'
  max_grad_norm: '1.0'
  gradient_accumulation_steps: '4'
  mixed_precision: fp16
  allow_tf32: 'False'
  guidance_scale: '7.0'
  val_guidance_scales: '[7.0]'
  use_deepspeed: 'False'
  zero_stage: '1'
  from_scratch: 'False'
  load_pretrained_model: None
  load_pretrained_model_ckpt: '-1'
  num_inference_steps: '50'
